# -*- coding: utf-8 -*-
"""LW1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xPJ1ilRgK4hu3q6OCcFAklQowRhG4VPV
"""

# импорт библиотек
import numpy as np
import matplotlib.pyplot as plt
import time

# ядро Епанечникова
def kernel(u): return np.where(np.abs(u) <= 1.0, 0.75 * (1.0 - u * u), 0.0)

# Оцениваем регрессию
def estimate(x_query, x_train, y_train, h):
    weights = kernel((x_query - x_train) / h)
    total = np.sum(weights)
    if total == 0: return 0 # чтобы на 0 не делилось
    return np.sum(weights * y_train) / total

# скользящий экзамен
def loocv_mse(x, y, beta, delta):
    h = delta / beta
    squared_errors = np.zeros(len(x))
    for i in range(len(x)):
        x_train = np.delete(x, i) # Исключаем i-ю точку по x
        y_train = np.delete(y, i) # Исключаем i-ю точку по y
        pred = estimate(x[i], x_train, y_train, h) # Предсказываем в оставленной точке
        squared_errors[i] = (y[i] - pred) ** 2
    return np.mean(squared_errors)

# Ищем лучшее beta
def find_best_beta(x, y, delta, beta_values):
    mses = [loocv_mse(x, y, beta, delta) for beta in beta_values]

    best_idx = np.argmin(mses)
    return beta_values[best_idx], mses[best_idx], np.array(mses)

# main
n = 80
x = np.random.uniform(-3, 7, n)
y = 0.1 * (x - 4) * np.cos(x) + 0.5 * x + np.random.normal(0, 0.3, n)
# вычисляем Delta — максимальный интервал между соседними точками
sorted_x = np.sort(x)
delta = np.max(np.diff(sorted_x))
print(f"Delta = {delta:.6f}")

beta_values = np.arange(0.1, 2.01, 0.1)
start_time = time.time()
best_beta, min_mse, all_mses = find_best_beta(x, y, delta, beta_values)
print(f"Оптимальное beta: {best_beta:.1f}")
print(f"Минимальная LOO-MSE: {min_mse:.4f}")
print(f"Время: {time.time() - start_time:.4f} с")

# Первый график (ошибка в зависимости от beta)
plt.figure(figsize=(10, 5))
plt.plot(beta_values, all_mses, 'o-', linewidth=2, markersize=6, color='purple')
plt.xlabel('Параметр размытия ядра beta')
plt.ylabel('MSE')
plt.title('Зависимость ошибки прогноза от beta')
plt.grid(True)
plt.xticks(beta_values)
plt.show()

# Второй график (данные и итоговая модель)
h_opt = delta / best_beta
x_grid = np.linspace(-3, 7, 300)
y_pred_grid = np.array([estimate(xi, x, y, h_opt) for xi in x_grid])

plt.figure(figsize=(11, 6))
plt.scatter(x, y, s=25, alpha=0.75, color='blue', label='Данные (с шумом)')
plt.plot(x_grid, y_pred_grid, 'r-', linewidth=3,
         label=f'НПР (β={best_beta:.1f}, h={h_opt:.3f})')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Непараметрическая регрессия Розенблатта–Парзена')
plt.legend()
plt.grid(True)
plt.show()